project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - Plano/PlanoIC02.qmd
    - "IdentificacaoMotorGerador/Motor Gerador Indentificação.ipynb"

website:
  title: "Controle de Conversores CC-CC"
  site-url: https://raphateixeira.github.io/ControleCC2CC/
  repo-url: https://github.com/raphateixeira/ControleCC2CC

format:
  html:
    theme: [cosmo, TemaRTx.scss]
    lang: pt-BR
    toc: true
